### ISSUE TITLE
Definir permisos

### ISSUE THREAD

**Issue by rafelsalgueiro** [aleex0309/parKING#12]
parking_admin: crear spots, modificarlos, permetre reservar amb qualsevol vehicle. 

Usuari: Reservar parking amb el SEU vehicle(s) i gestionar les seves reserves.

**Comment by aleex0309** [comment]
Me pongo con ello

**Comment by aleex0309** [comment]
Els usuaris poden modificar, per codi revisar que sigui ell qui ho modifica
